<script setup>
import { ref, nextTick, onMounted, onBeforeUnmount, onActivated } from 'vue'
import { useLabStore } from '../stores/labStore'
import { filterInventory } from '../utils/inventoryFilter'
import { esc, sanitize } from '../utils/htmlSafe'
import { invChip } from '../utils/invChip'
import { parseOnp } from '../utils/onpImport'
import * as XLSX from 'xlsx'
import { buildPlateRows, buildWellSummary, buildPlateGrid, plateToYaml, plateExportFilename, plateDims } from '../utils/plateExport'
import { parseWellHtml, buildWellHtml, withFinalConcentrations, totalVolume, fmtConc,
         collectPlateStocks, applyStockToPlate, unlinkedVolumes, scaleEntriesToTotal } from '../utils/wellComposition'
import ExpStatusPicker from './ExpStatusPicker.vue'
import { usePlanWorkspace } from '../composables/usePlanWorkspace'
import CloudLibraryModal from './CloudLibraryModal.vue'

import { BOEKHOVEN_PALETTE, assignColors } from '../utils/palette'

const store = useLabStore()

// ── Optional "colour by condition" overlay (Okabe-Ito) ──
// Groups wells by a key derived from their content (first text line), assigns
// each distinct group an Okabe-Ito colour, and renders a legend. Purely a view
// layer — the well content is untouched.
function wellText(html) {
  const div = document.createElement('div')
  div.innerHTML = html || ''
  return (div.textContent || '').trim().split('\n')[0].trim()
}
function plateGroups(plate) {
  const keys = []
  for (const wId of Object.keys(plate.wells || {})) {
    const k = wellText(plate.wells[wId])
    if (k && !keys.includes(k)) keys.push(k)
  }
  return { keys, colorMap: assignColors(BOEKHOVEN_PALETTE, keys) }
}
function wellColor(plate, wId) {
  if (!plate.colorByCondition) return ''
  const k = wellText(plate.wells?.[wId])
  if (!k) return ''
  return plateGroups(plate).colorMap[k] || ''
}
const activeDropdown = ref(null)
const showCloudLibrary = ref(false)

// Workspace behaviour (open / close / archive / duplicate / status) is shared by
// all plan modules — see composables/usePlanWorkspace.js.
const { loadFromCloud, closeInWorkspace, archivePlan, duplicatePlan, setStatus: setPlanStatus } =
    usePlanWorkspace({ store, table: 'plates', open: 'wellPlates', archived: 'archivedPlates', noun: 'well plate', showLibrary: showCloudLibrary })
const showOnpSettings = ref(false)

// Grouped multi-plate .onp export
const showGroupExport = ref(false)
const groupExportName = ref('Grouped Plates')
const groupSelection = ref({})   // plateId -> boolean

// UUIDs come from observing .onp files generated by Andrew+ (not from decompilation).
// Users can update these here if their installation uses different catalog identifiers.
const onpConfig = ref({
  waterReagentUuid:        '44fb2f8b-7d33-4bc0-8b51-0a1fd26b63ec',
  defaultSourceLabwareUuid: 'eda1c3ac-a089-4244-b0bc-9e5beb322475',
  waterSourceLabwareUuid:  '201812181100'
})

// --- Helper Functions ---
// Geometry lives in plateExport so the grid you see and the grid that gets
// exported cannot drift apart when a format is added.
const getPlateRows = (format) => plateDims(format).rows
const getPlateCols = (format) => plateDims(format).cols
const getWellId = (r, c) => { return String.fromCharCode(65 + r) + (c + 1); }

const filterBlockInventory = (query, scope) => filterInventory(store.inventory, query, scope)

// Lab and Private stocks are separate shelves, and filterInventory deliberately
// searches one at a time. A picker restricted to one shelf silently hides the other —
// you cannot link the private EDC you actually used if the picker only knows the lab's.
// So search both by default and say which shelf every hit is on.
const SHELVES = { Global: { label: 'Lab', color: '#2563eb' }, Personal: { label: 'Private', color: '#7c3aed' } }
const shelfOf = (item) => (item && item.scope === 'Personal') ? 'Personal' : 'Global'

const stockPickList = (query) => {
    const scope = store.plateRefSearchScope === 'Personal' ? 'Personal' : 'Global'
    return filterInventory(store.inventory, query, scope).slice(0, 200)
}
// The shelf an already-linked stock sits on, for the plate-wide list.
const linkedShelf = (invId) => {
    const item = invId ? store.inventory.find(i => i.id === invId) : null
    return item ? shelfOf(item) : null
}

// --- Plate Management Actions ---
const addWellPlate = () => { 
    store.wellPlates.unshift({ 
        id: crypto.randomUUID(),
        name: 'New Plate', 
        format: 96, 
        selectedWell: null, 
        targetLabware: '201812181400', 
        wells: {},
        scope: 'Personal',
        owner_id: store.user.id
    });
    store.saveWorkspaceState(); 
}





// --- Robot Protocol (.onp) IMPORT — the inverse of the exporters below ---
// Reads a protocol back into plates: every PIPETTING step is replayed into the
// labware it targets, so the plate shows what the robot was actually told to do.
// Wells are rendered with the concentration each component REACHES (stock · volume
// / total volume, on the real total), which is the honest reading when a well was
// filled past the volume it was designed for.
const onpInputRef = ref(null)
const onpImportBusy = ref(false)

const importOnpFile = async (event) => {
    const file = event.target.files && event.target.files[0]
    event.target.value = ''
    if (!file) return
    onpImportBusy.value = true
    try {
        const text = await file.text()
        let protocol
        try { protocol = JSON.parse(text) }
        catch { alert(`“${file.name}” isn’t readable as a protocol — an .onp is a JSON file.`); return }

        const { plates, warnings } = parseOnp(protocol, { inventory: store.inventory })
        const created = []
        plates.forEach((p, i) => {
            const wells = {}
            Object.entries(p.wells).forEach(([wellId, entries]) => {
                // No design volume is assumed: a protocol only says what was pipetted, so
                // the concentrations shown are computed on each well's own real total.
                wells[wellId] = buildWellHtml(entries, { inventory: store.inventory, showFinal: true })
            })
            const vr = p.volumeRange
            const spread = vr ? (Math.abs(vr.max - vr.min) < 0.005
                ? `every well ${vr.min.toFixed(1)} µL`
                : `well totals ${vr.min.toFixed(1)}–${vr.max.toFixed(1)} µL — they are not all the same`) : ''
            const plate = {
                id: crypto.randomUUID(),
                name: plates.length > 1 ? p.name : (p.name || file.name.replace(/\.onp$/i, '')),
                format: p.format,
                selectedWell: null,
                targetLabware: p.targetLabware,
                wells,
                scope: 'Personal',
                owner_id: store.user?.id,
            }
            store.wellPlates.unshift(plate)
            created.push(`${plate.name} — ${Object.keys(wells).length} wells, ${plate.format}-well, ${spread}`)
        })
        store.saveWorkspaceState()

        const notes = warnings.length ? `\n\n${warnings.join('\n')}` : ''
        alert(`Imported ${plates.length} plate${plates.length === 1 ? '' : 's'} from ${file.name}:\n\n`
            + created.map(c => '· ' + c).join('\n')
            + `\n\nEach well shows the concentration it ACTUALLY reaches, computed from the volumes that were pipetted `
            + `into it — so a well that was overfilled reads weaker than it was designed for.`
            + `\n\nSet the plate's well volume in the composition panel to have overfilled wells flagged, and edit the `
            + `stock used in any well there if it differs from the inventory.`
            + `\n\nCompounds were re-linked to inventory by name — an .onp carries no stock codes, so check any that stayed grey.${notes}`)
    } catch (e) {
        alert(`Could not import this protocol: ${(e && e.message) || e}`)
    } finally {
        onpImportBusy.value = false
    }
}

// --- Per-well composition: what went in, and what it actually came out at ---
// The well's HTML stays the source of truth (the exporters and the usage tracker
// read it), so this is a structured view over it that writes straight back.
const wellRows = (plate) => {
    if (!plate?.selectedWell) return []
    return withFinalConcentrations(parseWellHtml(plate.wells[plate.selectedWell] || ''))
}
const wellTotal = (plate) => {
    if (!plate?.selectedWell) return 0
    return totalVolume(parseWellHtml(plate.wells[plate.selectedWell] || ''))
}
// Liquid the well names but that carries no chip. It is NOT in the Σ above, because
// the robot exporters skip it too — the Σ has to stay a description of the plate that
// will actually be built. Saying so is the point: an unexplained short total is what
// sent a user looking for a bug, and the honest answer is "this much is unlinked".
const wellUnlinked = (plate) => {
    if (!plate?.selectedWell) return { total: 0, names: '' }
    const rows = unlinkedVolumes(plate.wells[plate.selectedWell] || '')
    return {
        total: rows.reduce((s, r) => s + r.volume, 0),
        names: [...new Set(rows.map(r => r.name))].join(', '),
    }
}

// Editing the stock used in THIS well. The inventory is untouched: a well records
// what was pipetted into it, which may be an older or a freshly diluted stock.
const setWellEntry = (plate, index, field, value) => {
    if (!plate?.selectedWell) return
    const entries = parseWellHtml(plate.wells[plate.selectedWell] || '')
    if (!entries[index]) return
    const v = parseFloat(String(value).replace(',', '.'))
    if (field === 'unit') entries[index].unit = String(value || '').trim()
    else if (isFinite(v) && v >= 0) entries[index][field] = v
    else return
    plate.wells[plate.selectedWell] = buildWellHtml(entries, { inventory: store.inventory, showFinal: true })
    syncWellEditor(plate)
    store.saveWorkspaceState()
}

// Re-make the selected well at a different total volume. Every volume — fill-up
// included — is multiplied by the same factor, so every final concentration stays
// exactly what it was; only the amount of liquid changes. This is the second half
// of copying a well: paste it, then shrink it to the volume the new plate runs at.
const scaleWellTo = (plate, value) => {
    if (!plate?.selectedWell) return
    const target = parseFloat(String(value).replace(',', '.'))
    const entries = parseWellHtml(plate.wells[plate.selectedWell] || '')
    const scaled = scaleEntriesToTotal(entries, target)
    if (!scaled) {
        if (String(value).trim() !== '') store.toast?.('Nothing to scale — the well needs parsed volumes and a positive target')
        return
    }
    plate.wells[plate.selectedWell] = buildWellHtml(scaled, { inventory: store.inventory, showFinal: true })
    syncWellEditor(plate)
    store.saveWorkspaceState()
    store.toast?.(`Well ${plate.selectedWell} scaled to ${target} µL — same concentrations, adjusted volumes`)
}

// --- Stocks used across the whole plate ---
// A plate normally uses one bottle of each compound in every well, so the stock is a
// property of the plate, not of 96 separate wells. This lists what the plate uses and
// changes it everywhere at once — in particular it attaches an inventory item, which
// restores the data-inv-id the usage tracker keys traceability on (an imported .onp
// carries compound names but no stock codes, so those arrive unlinked).
const showPlateStocks = ref({})
const plateStocks = (plate) => collectPlateStocks(plate.wells || {})

const linkPlateStock = (plate, key, inv) => {
    const { wells, wellsChanged } = applyStockToPlate(plate.wells, key, { inv }, { inventory: store.inventory })
    plate.wells = wells
    activeDropdown.value = null
    if (plate.selectedWell) syncWellEditor(plate)
    store.saveWorkspaceState()
    store.toast?.(`Linked ${inv.name} in ${wellsChanged} well${wellsChanged === 1 ? '' : 's'}`)
}

const setPlateStock = (plate, key, field, value) => {
    const v = field === 'unit' ? String(value || '').trim() : parseFloat(String(value).replace(',', '.'))
    if (field !== 'unit' && !(isFinite(v) && v >= 0)) return
    const { wells } = applyStockToPlate(plate.wells, key, { [field]: v }, { inventory: store.inventory })
    plate.wells = wells
    if (plate.selectedWell) syncWellEditor(plate)
    store.saveWorkspaceState()
}

// Push the rebuilt HTML into the contenteditable so both views agree.
const syncWellEditor = (plate) => {
    nextTick(() => {
        const editor = document.getElementById('wellEditor_' + plate.id)
        if (editor) editor.innerHTML = plate.wells[plate.selectedWell] || ''
    })
}

const updateDefaultLabware = (plate) => {
    if (plate.format === 384) plate.targetLabware = '201901101700';
    else if (plate.format === 96) plate.targetLabware = '201812181400';
    else if (plate.format === 24) plate.targetLabware = '201901101715';
    else plate.targetLabware = '';
}

// --- Editor Logic ---
const selectWell = (plate, wellId) => {
    plate.selectedWell = wellId;
    nextTick(() => {
        const editor = document.getElementById('wellEditor_' + plate.id);
        if (editor) editor.innerHTML = sanitize(plate.wells[wellId] || '');
    });
}
const updateWellContent = (plate, event) => {
    if (!plate.selectedWell) return;
    plate.wells[plate.selectedWell] = sanitize(event.target.innerHTML);
}
const formatWellDoc = (plate, cmd, value = null) => {
    const editor = document.getElementById('wellEditor_' + plate.id);
    if (editor) editor.focus();
    document.execCommand(cmd, false, value);
    updateWellContent(plate, { target: editor });
}
// --- Copy a well between plates ---
// One clipboard for the whole module: copy the selected well in one plate, then
// select a well on any plate (the same one included) and paste. The HTML travels
// verbatim, inventory chips included, so exports and the usage tracker read the
// pasted well exactly like the original.
const wellClipboard = ref(null)   // { html, from }
const copyWell = (plate) => {
    if (!plate.selectedWell) return
    wellClipboard.value = {
        html: plate.wells[plate.selectedWell] || '',
        from: `${plate.name} · ${plate.selectedWell}`,
    }
    store.toast?.(`Copied ${plate.selectedWell} — select a well on any plate and paste`)
}
const pasteWell = (plate) => {
    if (!wellClipboard.value || !plate.selectedWell) return
    plate.wells[plate.selectedWell] = sanitize(wellClipboard.value.html)
    syncWellEditor(plate)
    store.saveWorkspaceState()
    store.toast?.(`Pasted ${wellClipboard.value.from} into ${plate.selectedWell}`)
}

const insertInventoryRefToWell = (plate) => {
    if (!store.selectedWellInvRef || !plate.selectedWell) return;
    const item = store.inventory.find(i => i.id === store.selectedWellInvRef);
    const editor = document.getElementById('wellEditor_' + plate.id);
    if (item && editor) {
        editor.focus();
        const html = `&nbsp;${invChip(item, { fmt: store.formatNum })}&nbsp;`;
        document.execCommand('insertHTML', false, html);
        plate.wells[plate.selectedWell] = sanitize(editor.innerHTML);
    }
    store.selectedWellInvRef = '';
}

// Delegated handler: clicking the × on any inv-ref chip removes it.
// Bound at document level since well editors are dynamically created per-plate.
const onWellEditorClick = (e) => {
    const target = e.target
    if (!target?.classList?.contains('inv-ref-remove')) return
    const editor = target.closest('[id^="wellEditor_"]')
    if (!editor) return
    target.closest('.inv-ref')?.remove()
    const plateId = editor.id.replace('wellEditor_', '')
    const plate = store.wellPlates.find(p => p.id === plateId)
    if (plate?.selectedWell) plate.wells[plate.selectedWell] = sanitize(editor.innerHTML)
}
// A contenteditable holds no binding back to state: it is filled when a well is
// clicked and never again. Anything that renders this panel with a well already
// selected — a browser refresh restoring the workspace, coming back from another
// module, or the Phase Map writing into the plate in the meantime — would
// otherwise show an empty or stale editor whose next blur writes that staleness
// back over the well's real content. So refill every open editor from state
// whenever this module (re)appears.
const syncAllWellEditors = () => nextTick(() => {
    for (const plate of store.wellPlates) {
        if (!plate.selectedWell) continue
        const editor = document.getElementById('wellEditor_' + plate.id)
        if (editor) editor.innerHTML = sanitize(plate.wells[plate.selectedWell] || '')
    }
})
onMounted(() => { document.addEventListener('click', onWellEditorClick); syncAllWellEditors() })
onActivated(syncAllWellEditors)
onBeforeUnmount(() => document.removeEventListener('click', onWellEditorClick))

// --- Integrations ---
const savePlateToJournal = (plate) => {
    let html = `<br><br><div style="border: 1px solid var(--border); padding: 15px; border-radius: var(--radius); background: var(--surface);">`;
    html += `<h3 style="margin-top: 0; color: var(--primary);"><i class="fas fa-border-all"></i> Plate Map: ${esc(plate.name)} (${esc(plate.format)}-Well)</h3>`;
    html += `<div class="table-responsive"><table style="width: 100%; border-collapse: collapse; font-size: 0.75rem; text-align: left; border: 1px solid var(--border);">`;

    const rows = getPlateRows(plate.format);
    const cols = getPlateCols(plate.format);

    html += `<tr><th style="border: 1px solid var(--border); background: var(--summary-bg); padding: 4px; text-align: center;"></th>`;
    for (let c = 0; c < cols; c++) html += `<th style="border: 1px solid var(--border); background: var(--summary-bg); padding: 4px; text-align: center; min-width: 80px;">${c + 1}</th>`;
    html += `</tr>`;

    let filledWells = 0;
    for (let r = 0; r < rows; r++) {
        const rowLabel = String.fromCharCode(65 + r);
        html += `<tr><th style="border: 1px solid var(--border); background: var(--summary-bg); padding: 4px; text-align: center;">${rowLabel}</th>`;
        for (let c = 0; c < cols; c++) {
            const wId = getWellId(r, c);
            const content = plate.wells[wId];
            if (content && content.trim() !== '') filledWells++;
            html += `<td style="border: 1px solid var(--border); padding: 4px; vertical-align: top;">${content || ''}</td>`;
        }
        html += `</tr>`;
    }
    html += `</table></div>`;
    if (filledWells === 0) html += `<p style="opacity: 0.7; font-style: italic; margin-top: 10px;">Plate is completely empty.</p>`;
    html += `</div><br>`;

    if (!store.appendToActiveJournal(html)) {
        alert('Please select an active journal entry first.');
        return;
    }
    alert('Successfully appended Plate Map to Lab Journal!');
}

// --- Spreadsheet / YAML export ------------------------------------------------
// The .onp export answers "what should the robot do"; these answer "what is in
// this plate", which is the question everyone else asks. Same parsed data, three
// sheets: the long rows to analyse, a per-well summary, and the grid to read.
const downloadBlob = (blob, filename) => {
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = filename
    document.body.appendChild(a); a.click()
    document.body.removeChild(a); URL.revokeObjectURL(url)
}

const exportPlateWorkbook = (plate) => {
    const rows = buildPlateRows(plate)
    if (!rows.length) { alert('This plate has no filled wells to export.'); return }

    const wb = XLSX.utils.book_new()

    // Long format first: it is the sheet a script will read, and the one that
    // survives being pasted into anything.
    const wsWells = XLSX.utils.json_to_sheet(rows, {
        header: ['well', 'row', 'column', 'compound', 'code', 'inventory_id', 'role',
                 'stock_conc', 'stock_unit', 'volume_ul', 'final_conc', 'final_unit',
                 'well_total_ul', 'linked_to_inventory'],
    })
    wsWells['!cols'] = [
        { wch: 6 }, { wch: 5 }, { wch: 7 }, { wch: 26 }, { wch: 9 }, { wch: 16 }, { wch: 11 },
        { wch: 11 }, { wch: 10 }, { wch: 10 }, { wch: 11 }, { wch: 10 }, { wch: 13 }, { wch: 18 },
    ]
    wsWells['!freeze'] = { xSplit: 0, ySplit: 1 }
    XLSX.utils.book_append_sheet(wb, wsWells, 'Wells')

    const wsSummary = XLSX.utils.json_to_sheet(buildWellSummary(plate), {
        header: ['well', 'components', 'total_ul', 'unlinked_ul', 'design_volume_ul', 'overfilled'],
    })
    wsSummary['!cols'] = [{ wch: 6 }, { wch: 12 }, { wch: 10 }, { wch: 12 }, { wch: 17 }, { wch: 11 }]
    XLSX.utils.book_append_sheet(wb, wsSummary, 'Well summary')

    const wsGrid = XLSX.utils.aoa_to_sheet(buildPlateGrid(plate))
    const { cols } = plateDims(plate.format)
    wsGrid['!cols'] = [{ wch: 4 }, ...Array.from({ length: cols }, () => ({ wch: 24 }))]
    XLSX.utils.book_append_sheet(wb, wsGrid, 'Plate map')

    const wsMeta = XLSX.utils.aoa_to_sheet([
        ['Plate', plate.name || 'Plate'],
        ['Format', plate.format ?? 96],
        ['Design volume (µL)', Number(plate.targetVolume) || ''],
        ['Exported', new Date().toLocaleString('de-DE')],
        [],
        ['Note', 'final_conc is computed on the well\'s real total, i.e. what it actually reached.'],
        ['Note', 'Rows with role "unlinked" carry no inventory chip: real liquid, excluded from'],
        ['', 'well_total_ul and skipped by the robot export, because nothing records their source.'],
    ])
    wsMeta['!cols'] = [{ wch: 20 }, { wch: 80 }]
    XLSX.utils.book_append_sheet(wb, wsMeta, 'About')

    const today = new Date().toISOString().split('T')[0]
    XLSX.writeFile(wb, plateExportFilename(plate, 'xlsx', today))
}

const exportPlateYaml = (plate) => {
    const yaml = plateToYaml(plate, { exportedAt: new Date().toISOString() })
    const today = new Date().toISOString().split('T')[0]
    downloadBlob(new Blob([yaml], { type: 'text/yaml;charset=utf-8' }),
                 plateExportFilename(plate, 'yaml', today))
}

// --- Robot Protocol (.onp) Export Engine ---
// `excluded` is a set of compound keys ('__WATER__' or lowercased name) to leave
// out of the protocol entirely. Everything else is pipetted at exactly the volume
// the plate states — nothing is rescaled, so a well that loses a component simply
// receives that much less liquid.
const exportAndrewPlus = (plate, excluded = null) => {
    if (plate.format === 'ibidi' || plate.format === 'pcr8') {
        alert("Robot protocol export is not available for Ibidi gamma chambers or 8 PCR strips.");
        return;
    }
    if (!plate || !plate.wells || Object.keys(plate.wells).length === 0) {
        alert("Plate is empty.");
        return;
    }

    const md5 = function(d) {
        let r = /[\x80-\xFF]/g;
        if (r.test(d)) d = unescape(encodeURI(d));
        let h0 = 0x67452301, h1 = 0xEFCDAB89, h2 = 0x98BADCFE, h3 = 0x10325476;
        const rots = [7, 12, 17, 22, 5, 9, 14, 20, 4, 11, 16, 23, 6, 10, 15, 21];
        const k = [];
        for (let i = 0; i <= 63; i++) k[i] = (Math.abs(Math.sin(i + 1)) * 0x100000000) | 0;
        let words = [];
        for (let i = 0; i < d.length; i++) words[i >> 2] |= (d.charCodeAt(i) & 0xFF) << ((i % 4) * 8);
        let len = d.length * 8;
        words[len >> 5] |= 0x80 << (len % 32);
        words[(((len + 64) >>> 9) << 4) + 14] = len;
        for (let i = 0; i < words.length; i += 16) {
            let a = h0, b = h1, c = h2, d2 = h3;
            for (let j = 0; j <= 63; j++) {
                let f, g = j;
                if (j < 16) { f = (b & c) | ((~b) & d2); }
                else if (j < 32) { f = (d2 & b) | ((~d2) & c); g = (5 * j + 1) % 16; }
                else if (j < 48) { f = b ^ c ^ d2; g = (3 * j + 5) % 16; }
                else { f = c ^ (b | (~d2)); g = (7 * j) % 16; }
                let temp = d2; d2 = c; c = b;
                let x = a + f + k[j] + (words[i + g] || 0);
                let rot = rots[(Math.floor(j / 16) * 4) + (j % 4)];
                b = b + ((x << rot) | (x >>> (32 - rot)));
                a = temp;
            }
            h0 = (h0 + a) | 0; h1 = (h1 + b) | 0; h2 = (h2 + c) | 0; h3 = (h3 + d2) | 0;
        }
        const hex = (x) => {
            let s = '';
            for (let i = 0; i < 4; i++) s += ((x >> (i * 8)) & 0xFF).toString(16).padStart(2, '0');
            return s;
        };
        return hex(h0) + hex(h1) + hex(h2) + hex(h3);
    };

    let transfers = [];
    const parser = new DOMParser();

    for (const [wId, html] of Object.entries(plate.wells)) {
        if (!html || html.trim() === '') continue;
        const doc = parser.parseFromString(html, 'text/html');

        const row = wId.charCodeAt(0) - 64;
        const col = parseInt(wId.substring(1));
        const destCavity = { row, column: col };

        const refs = doc.querySelectorAll('.inv-ref');
        refs.forEach(ref => {
            let text = ref.innerText;
            let labwareAttr = ref.getAttribute('data-labware');
            let labwareUuid = (labwareAttr && labwareAttr.trim() !== '') ? labwareAttr : onpConfig.value.defaultSourceLabwareUuid;

            let nameMatch = text.match(/\]\s*(.*?)\s*\(/);
            let name = nameMatch ? nameMatch[1].trim() : text.replace(/\[.*?\]/, '').replace(/\(.*?\)/, '').trim();

            let concValue = 100; let concUnit = "uM";
            let concMatch = text.match(/\(([\d\.,]+)\s*([^)]+)\)/);
            if (concMatch) {
                concValue = parseFloat(concMatch[1].replace(',', '.'));
                concUnit = concMatch[2].trim().replace('µ', 'u');
            }

            let nextText = ref.nextSibling ? ref.nextSibling.textContent : "";
            let volMatch = nextText.match(/([\d\.]+)\s*(µL|mL|L)/);
            if (name && volMatch) {
                let vol = parseFloat(volMatch[1]);
                if (volMatch[2] === 'mL') vol *= 1000;
                if (volMatch[2] === 'L') vol *= 1000000;
                if (vol > 0) transfers.push({ sourceName: name, destCavity, volume: vol, type: 'reagent', concValue: concValue, concUnit: concUnit, labwareUuid: labwareUuid });
            }
        });

        const strongs = doc.querySelectorAll('strong');
        strongs.forEach(st => {
            if (st.innerText.includes('MQ H₂O') || st.innerText.includes('MQ Water')) {
                let volText = "";
                if (st.nextElementSibling && st.nextElementSibling.tagName === 'SPAN') volText = st.nextElementSibling.innerText;
                else if (st.nextSibling && st.nextSibling.nodeType === Node.TEXT_NODE) volText = st.nextSibling.textContent;
                
                let volMatch = volText.match(/([\d\.]+)\s*(µL|mL|L)/);
                if (volMatch) {
                    let vol = parseFloat(volMatch[1]);
                    if(volMatch[2] === 'mL') vol *= 1000;
                    if(volMatch[2] === 'L') vol *= 1000000;
                    if (vol > 0) transfers.push({ sourceName: 'Water', destCavity, volume: vol, type: 'water', labwareUuid: onpConfig.value.waterSourceLabwareUuid });
                }
            }
        });
    }

    // Drop the compounds the export dialog unticked. The filter runs on the parsed
    // transfers, not the wells, so the plate itself is untouched.
    if (excluded && excluded.size) {
        transfers = transfers.filter(t => !excluded.has(t.type === 'water' ? '__WATER__' : t.sourceName.toLowerCase()));
    }

    if (transfers.length === 0) { alert("No pipetting transfers found in the plate."); return; }

    // Water must be pipetted first so other reagents are diluted into it
    transfers.sort((a, b) => (a.type === 'water' ? -1 : b.type === 'water' ? 1 : 0));

    const generateHex = (len) => [...Array(len)].map(() => Math.floor(Math.random() * 16).toString(16)).join('');
    const generateUUID = () => 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
        const r = Math.random() * 16 | 0, v = c === 'x' ? r : (r & 0x3 | 0x8);
        return v.toString(16);
    });

    const targetPlateRef = generateHex(16);
    const waterLabwareRef = generateHex(16);
    const waterReagentRef = generateHex(16);

    let defaultTargetUuid = plate.format === 384 ? '201901101700' : (plate.format === 24 ? '201901101715' : '201812181400');
    const targetLabwareUuid = plate.targetLabware || defaultTargetUuid;

    const labwares = [
        {
            ref: targetPlateRef, name: plate.name || "Target Plate", presentation: { position: { x: 3810, y: 3940 } },
            isTarget: false, throwAwayTipsAfterUse: false, labware: { uuid: targetLabwareUuid } 
        }
    ];

    const reagents = [];
    const sourceMap = {}; 
    const sourceDataMap = {};

    transfers.forEach(t => {
        if (t.type === 'reagent' && !sourceDataMap[t.sourceName]) sourceDataMap[t.sourceName] = { concValue: t.concValue, concUnit: t.concUnit };
        const sourceKey = t.sourceName + '_' + t.labwareUuid;
        if (!sourceMap[sourceKey]) {
            sourceMap[sourceKey] = {
                labwareRef: t.type === 'water' ? waterLabwareRef : generateHex(16),
                reagentRef: t.type === 'water' ? waterReagentRef : generateHex(16),
                labwareUuid: t.labwareUuid, sourceName: t.sourceName, isWater: t.type === 'water'
            };
        }
        t.sourceKey = sourceKey;
    });

    let idx = 0;
    for (const [key, data] of Object.entries(sourceMap)) {
        labwares.push({
            ref: data.labwareRef, name: data.isWater ? "Water" : data.sourceName,
            presentation: { position: { x: 3860 + (idx * 220 % 800), y: 3700 + Math.floor(idx/4)*180 } },
            isTarget: false, throwAwayTipsAfterUse: false, labware: { uuid: data.labwareUuid } 
        });

        const reagentPayload = {
            uuid: data.isWater ? onpConfig.value.waterReagentUuid : generateUUID(),
            name: data.isWater ? "Water" : data.sourceName,
            concentrationValue: data.isWater ? "1.000" : (sourceDataMap[data.sourceName] ? sourceDataMap[data.sourceName].concValue.toString() : "100.000"),
            concentrationUnit: data.isWater ? "au" : (sourceDataMap[data.sourceName] ? sourceDataMap[data.sourceName].concUnit : "uM"),
            color: Math.floor(Math.random() * 16777215), sample: false
        };

        if (!data.isWater) { reagentPayload.description = ""; reagentPayload.link = ""; }
        reagents.push({ isReagent: true, ref: data.reagentRef, reagent: reagentPayload });
        idx++;
    }

    const initialVolumes = {};
    transfers.forEach(t => { initialVolumes[t.sourceKey] = (initialVolumes[t.sourceKey] || 0) + t.volume; });

    const labwareStates = {};
    labwareStates[targetPlateRef] = { labwareRef: targetPlateRef, cavityStates: {}, inError: false };

    for (const [key, data] of Object.entries(sourceMap)) {
        const totalVol = Number((initialVolumes[key] * 1.2).toFixed(3)); 
        labwareStates[data.labwareRef] = {
            labwareRef: data.labwareRef,
            cavityStates: {
                "1-1": {
                    cavity: { row: 1, column: 1 },
                    solution: {
                        volume: { value: totalVol, unit: "uL" },
                        color: reagents.find(r => r.ref === data.reagentRef).reagent.color,
                        content: {
                            [data.reagentRef]: {
                                reagentRef: data.reagentRef, origins: [`${data.labwareRef}_A1`], dilutionFactor: 1,
                                volume: { value: totalVol, unit: "uL" }, color: reagents.find(r => r.ref === data.reagentRef).reagent.color
                            }
                        }
                    },
                    auto: true
                }
            },
            inError: false
        };
    }

    const steps = [{ index: 0, state: { labwareStates, errors: [], warnings: [] }, ref: generateHex(16), groupStepRefs: [] }];

    const groupedTransfers = {};
    transfers.forEach(t => {
        const formattedVol = Number(t.volume.toFixed(3));
        const key = `${t.sourceKey}_${formattedVol}`;
        if (!groupedTransfers[key]) groupedTransfers[key] = { sourceKey: t.sourceKey, volume: formattedVol, cavities: [] };
        groupedTransfers[key].cavities.push(t.destCavity);
    });

    // Steps run water first, then one compound at a time in alphabetical order —
    // not in the order wells happened to mention them, which scattered a compound's
    // steps through the protocol. On the bench that order is the natural one: fetch
    // a stock once, pipette everything it feeds, put it away.
    const orderedGroups = Object.values(groupedTransfers).sort((a, b) => {
        const sa = sourceMap[a.sourceKey], sb = sourceMap[b.sourceKey];
        if (sa.isWater !== sb.isWater) return sa.isWater ? -1 : 1;
        const byName = (sa.sourceName || '').localeCompare(sb.sourceName || '', undefined, { sensitivity: 'base' });
        return byName !== 0 ? byName : a.volume - b.volume;
    });

    let stepIdx = 1;
    for (const group of orderedGroups) {
        const srcData = sourceMap[group.sourceKey];
        // Emit one step per de-duplicated round so a well never repeats within a step.
        for (const roundCavities of onpCavityRounds(group.cavities)) {
            steps.push({
                index: stepIdx++, actionTypeId: "PIPETTING",
                action: {
                    type: "PIPETTING",
                    sources: [{ labwareRef: srcData.labwareRef, cavities: [{ row: 1, column: 1 }], customPipettingPolicy: false }],
                    destinations: [{ labwareRef: targetPlateRef, cavities: roundCavities, customPipettingPolicy: false }],
                    params: {
                        volume: { value: group.volume, unit: "uL" }, mode: "forward", aspirationSpeed: "normal", dispensingSpeed: "normal",
                        airTopCushion: false, airBottomCushion: false, tipChangeBeginning: true, tipChangeBetween: true, tipWithFilter: false,
                        movingSpeed: "normal", verifyTip: false, blowOut: true, blowOutPause: false, tipTouch: false, armSpeed: "normal",
                        preciseAspirationSpeed: 5, preciseDispensingSpeed: 5, preciseFluidicSpeedEnabled: false
                    },
                    mixingSource: { enabled: false, times: 3, speed: "normal", volume: { value: 0, unit: "uL" }, preciseSpeed: 5, preciseSpeedEnabled: false },
                    tipPositionSource: { position: "liquid", customHeight: false, customHeightValue: 0, avoidTouch: false },
                    mixingDest: { enabled: false, times: 3, speed: "normal", volume: { value: 0, unit: "uL" }, preciseSpeed: 5, preciseSpeedEnabled: false },
                    tipPositionDest: { position: "bottom", customHeight: false, customHeightValue: 0, avoidTouch: false }
                },
                ref: generateHex(16), groupStepRefs: []
            });
        }
    }

    const baseProtocol = {
        name: plate.name || "Exported Protocol", description: "Exported from CTI Lab Assistant",
        params: { pipettingPolicy: "rbr", filterTips: false, safeTipOverfly: false }, errors: 0,
        steps: steps, labwares: labwares, reagents: reagents, samples: [], pipettingPolicy: "rbr", isDynamic: false, version: "1.2.0"
    };

    const jsonStr = JSON.stringify(baseProtocol);
    baseProtocol.checksum = md5(jsonStr);

    const blob = new Blob([JSON.stringify(baseProtocol)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url; link.download = `RobotProtocol_${plate.name.replace(/\s+/g, '_')}.onp`;
    document.body.appendChild(link); link.click(); document.body.removeChild(link);
}

// --- Per-export compound selection ---
// The .onp button opens a dialog listing every compound the protocol would
// pipette, each with its demand summed across the plate. Unticking one leaves it
// out of the protocol; every other volume is exported unchanged. The list is
// built by the SAME parser the exporter runs on (onpParsePlateTransfers uses the
// identical regexes), so what the dialog shows is exactly what would be pipetted.
const onpExportModal = ref(null)   // { plateId, plateName, items: [{ key, label, isWater, volume, wells, included }] }

const openOnpExportModal = (plate) => {
    if (plate.format === 'ibidi' || plate.format === 'pcr8') {
        alert("Robot protocol export is not available for Ibidi gamma chambers or 8 PCR strips.");
        return;
    }
    const transfers = onpParsePlateTransfers(plate)
    if (!transfers.length) { alert("No pipetting transfers found in the plate."); return }

    const byKey = new Map()
    transfers.forEach(t => {
        const key = t.type === 'water' ? '__WATER__' : t.sourceName.toLowerCase()
        if (!byKey.has(key)) {
            byKey.set(key, { key, label: t.type === 'water' ? 'Water (MQ H₂O)' : t.sourceName,
                             isWater: t.type === 'water', volume: 0, wellSet: new Set(), included: true })
        }
        const g = byKey.get(key)
        g.volume += t.volume
        g.wellSet.add(`${t.destCavity.row}-${t.destCavity.column}`)
    })
    const items = [...byKey.values()]
        .sort((a, b) => a.isWater !== b.isWater ? (a.isWater ? -1 : 1)
            : a.label.localeCompare(b.label, undefined, { sensitivity: 'base' }))
        .map(({ wellSet, ...g }) => ({ ...g, wells: wellSet.size }))
    onpExportModal.value = { plateId: plate.id, plateName: plate.name, items }
}

const confirmOnpExport = () => {
    const m = onpExportModal.value
    if (!m) return
    const plate = store.wellPlates.find(p => p.id === m.plateId)
    onpExportModal.value = null
    if (!plate) return
    exportAndrewPlus(plate, new Set(m.items.filter(i => !i.included).map(i => i.key)))
}

// --- Grouped Multi-Plate Robot Protocol (.onp) Export ---
// Combines several well plates into ONE .onp. Each plate becomes its own target
// labware, but sources are de-duplicated GLOBALLY by stock identity (code + name):
// a stock shared between plates appears once, holds the summed volume of all plates,
// and every plate's pipetting steps draw from that single source labware.
// This path is fully independent — the single-plate exportAndrewPlus is untouched.

const onpMd5 = function(d) {
    let r = /[\x80-\xFF]/g;
    if (r.test(d)) d = unescape(encodeURI(d));
    let h0 = 0x67452301, h1 = 0xEFCDAB89, h2 = 0x98BADCFE, h3 = 0x10325476;
    const rots = [7, 12, 17, 22, 5, 9, 14, 20, 4, 11, 16, 23, 6, 10, 15, 21];
    const k = [];
    for (let i = 0; i <= 63; i++) k[i] = (Math.abs(Math.sin(i + 1)) * 0x100000000) | 0;
    let words = [];
    for (let i = 0; i < d.length; i++) words[i >> 2] |= (d.charCodeAt(i) & 0xFF) << ((i % 4) * 8);
    let len = d.length * 8;
    words[len >> 5] |= 0x80 << (len % 32);
    words[(((len + 64) >>> 9) << 4) + 14] = len;
    for (let i = 0; i < words.length; i += 16) {
        let a = h0, b = h1, c = h2, d2 = h3;
        for (let j = 0; j <= 63; j++) {
            let f, g = j;
            if (j < 16) { f = (b & c) | ((~b) & d2); }
            else if (j < 32) { f = (d2 & b) | ((~d2) & c); g = (5 * j + 1) % 16; }
            else if (j < 48) { f = b ^ c ^ d2; g = (3 * j + 5) % 16; }
            else { f = c ^ (b | (~d2)); g = (7 * j) % 16; }
            let temp = d2; d2 = c; c = b;
            let x = a + f + k[j] + (words[i + g] || 0);
            let rot = rots[(Math.floor(j / 16) * 4) + (j % 4)];
            b = b + ((x << rot) | (x >>> (32 - rot)));
            a = temp;
        }
        h0 = (h0 + a) | 0; h1 = (h1 + b) | 0; h2 = (h2 + c) | 0; h3 = (h3 + d2) | 0;
    }
    const hex = (x) => {
        let s = '';
        for (let i = 0; i < 4; i++) s += ((x >> (i * 8)) & 0xFF).toString(16).padStart(2, '0');
        return s;
    };
    return hex(h0) + hex(h1) + hex(h2) + hex(h3);
};

const onpHex = (len) => [...Array(len)].map(() => Math.floor(Math.random() * 16).toString(16)).join('');
const onpUuid = () => 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
    const r = Math.random() * 16 | 0, v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
});

// Split a step's cavity list into "rounds" so a given well never appears twice within
// one PIPETTING step. A well that receives the same stock+volume N times (e.g. a matrix
// diagonal cell fed by both its row and its column component) is spread across N steps —
// the robot still dispenses it N times (total volume unchanged), but no single step lists
// the same well twice. Duplicate cavities in one step otherwise serialise as overlapping
// cavity ranges (e.g. "E1:E5, E5:E7") that Andrew+ / OneLab mis-expands, double-counting
// the wells around the overlap and reporting inflated well volumes.
// Declared as a function so it is hoisted for use by exportAndrewPlus (defined above).
function onpCavityRounds(cavities) {
    const rounds = [];
    const seen = [];
    for (const cav of cavities) {
        const id = `${cav.row}-${cav.column}`;
        let r = 0;
        while (seen[r] && seen[r].has(id)) r++;
        if (!seen[r]) { seen[r] = new Set(); rounds[r] = []; }
        seen[r].add(id);
        rounds[r].push(cav);
    }
    return rounds;
}

// Parse a single plate's wells into a flat transfer list. Mirrors the parsing in
// exportAndrewPlus but additionally extracts the stock [code] for cross-plate dedup.
const onpParsePlateTransfers = (plate) => {
    const transfers = [];
    const parser = new DOMParser();
    for (const [wId, html] of Object.entries(plate.wells || {})) {
        if (!html || html.trim() === '') continue;
        const doc = parser.parseFromString(html, 'text/html');
        const row = wId.charCodeAt(0) - 64;
        const col = parseInt(wId.substring(1));
        const destCavity = { row, column: col };

        doc.querySelectorAll('.inv-ref').forEach(ref => {
            let text = ref.innerText;
            let labwareAttr = ref.getAttribute('data-labware');
            let labwareUuid = (labwareAttr && labwareAttr.trim() !== '') ? labwareAttr : onpConfig.value.defaultSourceLabwareUuid;

            let codeMatch = text.match(/\[(.*?)\]/);
            let code = codeMatch ? codeMatch[1].trim() : '';

            let nameMatch = text.match(/\]\s*(.*?)\s*\(/);
            let name = nameMatch ? nameMatch[1].trim() : text.replace(/\[.*?\]/, '').replace(/\(.*?\)/, '').trim();

            let concValue = 100; let concUnit = "uM";
            let concMatch = text.match(/\(([\d\.,]+)\s*([^)]+)\)/);
            if (concMatch) {
                concValue = parseFloat(concMatch[1].replace(',', '.'));
                concUnit = concMatch[2].trim().replace('µ', 'u');
            }

            let nextText = ref.nextSibling ? ref.nextSibling.textContent : "";
            let volMatch = nextText.match(/([\d\.]+)\s*(µL|mL|L)/);
            if (name && volMatch) {
                let vol = parseFloat(volMatch[1]);
                if (volMatch[2] === 'mL') vol *= 1000;
                if (volMatch[2] === 'L') vol *= 1000000;
                if (vol > 0) transfers.push({ sourceName: name, code, destCavity, volume: vol, type: 'reagent', concValue, concUnit, labwareUuid });
            }
        });

        doc.querySelectorAll('strong').forEach(st => {
            if (st.innerText.includes('MQ H₂O') || st.innerText.includes('MQ Water')) {
                let volText = "";
                if (st.nextElementSibling && st.nextElementSibling.tagName === 'SPAN') volText = st.nextElementSibling.innerText;
                else if (st.nextSibling && st.nextSibling.nodeType === Node.TEXT_NODE) volText = st.nextSibling.textContent;
                let volMatch = volText.match(/([\d\.]+)\s*(µL|mL|L)/);
                if (volMatch) {
                    let vol = parseFloat(volMatch[1]);
                    if (volMatch[2] === 'mL') vol *= 1000;
                    if (volMatch[2] === 'L') vol *= 1000000;
                    if (vol > 0) transfers.push({ sourceName: 'Water', code: '', destCavity, volume: vol, type: 'water', labwareUuid: onpConfig.value.waterSourceLabwareUuid });
                }
            }
        });
    }
    return transfers;
};

// Plates eligible for grouped export (robot-compatible format and non-empty).
const exportableGroupPlates = () => store.wellPlates.filter(p =>
    p.format !== 'ibidi' && p.format !== 'pcr8' &&
    p.wells && Object.keys(p.wells).some(w => p.wells[w] && p.wells[w].trim() !== '')
);

const openGroupExport = () => {
    const sel = {};
    exportableGroupPlates().forEach(p => { sel[p.id] = groupSelection.value[p.id] ?? true; });
    groupSelection.value = sel;
    showGroupExport.value = true;
};

const exportAndrewPlusMulti = () => {
    const plates = exportableGroupPlates().filter(p => groupSelection.value[p.id]);
    if (plates.length < 2) { alert("Select at least two plates to group into one .onp file."); return; }

    // Shared water identifiers — one Water source across every plate.
    const waterLabwareRef = onpHex(16);
    const waterReagentRef = onpHex(16);

    const labwares = [];
    const labwareStates = {};
    const allTransfers = [];

    // One target labware (+ empty state) per plate; tag each transfer with its plate.
    plates.forEach((plate, i) => {
        const targetPlateRef = onpHex(16);
        const defaultTargetUuid = plate.format === 384 ? '201901101700' : (plate.format === 24 ? '201901101715' : '201812181400');
        const targetLabwareUuid = plate.targetLabware || defaultTargetUuid;
        labwares.push({
            ref: targetPlateRef, name: plate.name || `Target Plate ${i + 1}`,
            presentation: { position: { x: 3810 + i * 280, y: 3940 } },
            isTarget: false, throwAwayTipsAfterUse: false, labware: { uuid: targetLabwareUuid }
        });
        labwareStates[targetPlateRef] = { labwareRef: targetPlateRef, cavityStates: {}, inError: false };

        onpParsePlateTransfers(plate).forEach(t => { t.plateRef = targetPlateRef; allTransfers.push(t); });
    });

    if (allTransfers.length === 0) { alert("No pipetting transfers found in the selected plates."); return; }

    // Water must be pipetted first so other reagents are diluted into it.
    allTransfers.sort((a, b) => (a.type === 'water' ? 0 : 1) - (b.type === 'water' ? 0 : 1));

    // Global source dedup: water → one shared key; reagents → code + name.
    const stockKey = (t) => t.type === 'water'
        ? 'WATER'
        : `${(t.code || '').toLowerCase()}||${(t.sourceName || '').toLowerCase()}`;

    const sourceMap = {};
    const sourceDataMap = {};
    allTransfers.forEach(t => {
        const sourceKey = stockKey(t);
        if (t.type === 'reagent' && !sourceDataMap[sourceKey]) sourceDataMap[sourceKey] = { concValue: t.concValue, concUnit: t.concUnit };
        if (!sourceMap[sourceKey]) {
            sourceMap[sourceKey] = {
                labwareRef: t.type === 'water' ? waterLabwareRef : onpHex(16),
                reagentRef: t.type === 'water' ? waterReagentRef : onpHex(16),
                labwareUuid: t.labwareUuid, sourceName: t.sourceName, code: t.code, isWater: t.type === 'water'
            };
        }
        t.sourceKey = sourceKey;
    });

    // Source labwares + reagents (one per unique stock).
    const reagents = [];
    let idx = 0;
    for (const [key, data] of Object.entries(sourceMap)) {
        labwares.push({
            ref: data.labwareRef, name: data.isWater ? "Water" : data.sourceName,
            presentation: { position: { x: 3860 + (idx * 220 % 800), y: 3300 + Math.floor(idx / 4) * 180 } },
            isTarget: false, throwAwayTipsAfterUse: false, labware: { uuid: data.labwareUuid }
        });
        const reagentPayload = {
            uuid: data.isWater ? onpConfig.value.waterReagentUuid : onpUuid(),
            name: data.isWater ? "Water" : data.sourceName,
            concentrationValue: data.isWater ? "1.000" : (sourceDataMap[key] ? sourceDataMap[key].concValue.toString() : "100.000"),
            concentrationUnit: data.isWater ? "au" : (sourceDataMap[key] ? sourceDataMap[key].concUnit : "uM"),
            color: Math.floor(Math.random() * 16777215), sample: false
        };
        if (!data.isWater) { reagentPayload.description = ""; reagentPayload.link = ""; }
        reagents.push({ isReagent: true, ref: data.reagentRef, reagent: reagentPayload });
        idx++;
    }

    // Initial source volumes = summed demand across ALL plates (+20% headroom).
    const initialVolumes = {};
    allTransfers.forEach(t => { initialVolumes[t.sourceKey] = (initialVolumes[t.sourceKey] || 0) + t.volume; });

    for (const [key, data] of Object.entries(sourceMap)) {
        const totalVol = Number((initialVolumes[key] * 1.2).toFixed(3));
        const reagentColor = reagents.find(r => r.ref === data.reagentRef).reagent.color;
        labwareStates[data.labwareRef] = {
            labwareRef: data.labwareRef,
            cavityStates: {
                "1-1": {
                    cavity: { row: 1, column: 1 },
                    solution: {
                        volume: { value: totalVol, unit: "uL" }, color: reagentColor,
                        content: {
                            [data.reagentRef]: {
                                reagentRef: data.reagentRef, origins: [`${data.labwareRef}_A1`], dilutionFactor: 1,
                                volume: { value: totalVol, unit: "uL" }, color: reagentColor
                            }
                        }
                    },
                    auto: true
                }
            },
            inError: false
        };
    }

    const steps = [{ index: 0, state: { labwareStates, errors: [], warnings: [] }, ref: onpHex(16), groupStepRefs: [] }];

    // Group transfers by source + destination plate + volume → one PIPETTING step each.
    // Repeated (well, stock, volume) transfers are intentional and must NOT be collapsed:
    // the matrix can add the same stock to a well as both a row and a column component
    // (e.g. "H" twice at 0.633 µL → 1.266 µL total). Listing the cavity once per transfer
    // makes the robot dispense each portion so the volumes sum — mirroring the single-plate
    // export exactly, which is the verified-correct reference.
    const groupedTransfers = {};
    allTransfers.forEach(t => {
        const formattedVol = Number(t.volume.toFixed(3));
        const key = `${t.sourceKey}__${t.plateRef}__${formattedVol}`;
        if (!groupedTransfers[key]) groupedTransfers[key] = { sourceKey: t.sourceKey, plateRef: t.plateRef, volume: formattedVol, cavities: [] };
        groupedTransfers[key].cavities.push(t.destCavity);
    });

    // Same step order as the single-plate export: water first, then compounds
    // alphabetically, all of one compound's steps together. The sort is stable, so
    // within one compound the plates keep the order they were selected in.
    const orderedGroups = Object.values(groupedTransfers).sort((a, b) => {
        const sa = sourceMap[a.sourceKey], sb = sourceMap[b.sourceKey];
        if (sa.isWater !== sb.isWater) return sa.isWater ? -1 : 1;
        const byName = (sa.sourceName || '').localeCompare(sb.sourceName || '', undefined, { sensitivity: 'base' });
        return byName !== 0 ? byName : a.volume - b.volume;
    });

    let stepIdx = 1;
    for (const group of orderedGroups) {
        const srcData = sourceMap[group.sourceKey];
        // Emit one step per de-duplicated round so a well never repeats within a step.
        for (const roundCavities of onpCavityRounds(group.cavities)) {
            steps.push({
                index: stepIdx++, actionTypeId: "PIPETTING",
                action: {
                    type: "PIPETTING",
                    sources: [{ labwareRef: srcData.labwareRef, cavities: [{ row: 1, column: 1 }], customPipettingPolicy: false }],
                    destinations: [{ labwareRef: group.plateRef, cavities: roundCavities, customPipettingPolicy: false }],
                    params: {
                        volume: { value: group.volume, unit: "uL" }, mode: "forward", aspirationSpeed: "normal", dispensingSpeed: "normal",
                        airTopCushion: false, airBottomCushion: false, tipChangeBeginning: true, tipChangeBetween: true, tipWithFilter: false,
                        movingSpeed: "normal", verifyTip: false, blowOut: true, blowOutPause: false, tipTouch: false, armSpeed: "normal",
                        preciseAspirationSpeed: 5, preciseDispensingSpeed: 5, preciseFluidicSpeedEnabled: false
                    },
                    mixingSource: { enabled: false, times: 3, speed: "normal", volume: { value: 0, unit: "uL" }, preciseSpeed: 5, preciseSpeedEnabled: false },
                    tipPositionSource: { position: "liquid", customHeight: false, customHeightValue: 0, avoidTouch: false },
                    mixingDest: { enabled: false, times: 3, speed: "normal", volume: { value: 0, unit: "uL" }, preciseSpeed: 5, preciseSpeedEnabled: false },
                    tipPositionDest: { position: "bottom", customHeight: false, customHeightValue: 0, avoidTouch: false }
                },
                ref: onpHex(16), groupStepRefs: []
            });
        }
    }

    const protocolName = (groupExportName.value || "Grouped Protocol").trim() || "Grouped Protocol";
    const baseProtocol = {
        name: protocolName, description: "Exported from CTI Lab Assistant",
        params: { pipettingPolicy: "rbr", filterTips: false, safeTipOverfly: false }, errors: 0,
        steps, labwares, reagents, samples: [], pipettingPolicy: "rbr", isDynamic: false, version: "1.2.0"
    };

    baseProtocol.checksum = onpMd5(JSON.stringify(baseProtocol));

    const blob = new Blob([JSON.stringify(baseProtocol)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url; link.download = `RobotProtocol_${protocolName.replace(/\s+/g, '_')}.onp`;
    document.body.appendChild(link); link.click(); document.body.removeChild(link);
    showGroupExport.value = false;
};
</script>

<template>
  <div class="card">
    
    <CloudLibraryModal :show="showCloudLibrary" title="Plate Library" noun="plates"
                       :items="store.cloudPlates" table="plates"
                       @close="showCloudLibrary = false" @open="loadFromCloud" />

    <!-- Single-plate .onp export: pick which compounds to pipette -->
    <div v-if="onpExportModal" style="position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.6); display: flex; align-items: center; justify-content: center; z-index: 2000;">
        <div style="background: var(--surface); padding: 25px; border-radius: var(--radius); border: 1px solid var(--border); max-width: 520px; width: 90%; max-height: 80vh; overflow-y: auto;">
            <div class="flex-between" style="border-bottom: 1px solid var(--ln); padding-bottom: 10px; margin-bottom: 15px;">
                <h3 style="margin: 0; color: var(--primary);"><i class="fas fa-robot"></i> Export .onp — {{ onpExportModal.plateName }}</h3>
                <button class="danger small" @click="onpExportModal = null"><i class="fas fa-times"></i></button>
            </div>

            <p style="margin: 0 0 14px 0; font-size: 0.82rem; opacity: 0.75;">
                Untick a compound to leave it out of the protocol. Every other volume is pipetted
                exactly as the plate states — nothing is rescaled, so a well that loses a component
                simply receives that much less liquid.
            </p>

            <div style="display: flex; flex-direction: column; gap: 6px; margin-bottom: 18px;">
                <label v-for="it in onpExportModal.items" :key="it.key"
                       style="display: flex; align-items: center; gap: 10px; background: var(--panel-bg); padding: 8px 10px; border-radius: var(--radius); border: 1px solid var(--border); cursor: pointer;"
                       :style="it.included ? '' : 'opacity: 0.5;'">
                    <input type="checkbox" v-model="it.included" style="width: 16px; height: 16px;" />
                    <i class="fas" :class="it.isWater ? 'fa-droplet' : 'fa-vial'" style="opacity: 0.5; width: 14px;"></i>
                    <strong style="flex-grow: 1; font-size: 0.9rem;" :style="it.included ? '' : 'text-decoration: line-through;'">{{ it.label }}</strong>
                    <span style="font-size: 0.72rem; opacity: 0.7; white-space: nowrap;">
                        {{ it.wells }} well{{ it.wells === 1 ? '' : 's' }} · {{ it.volume.toFixed(1) }} µL
                    </span>
                </label>
            </div>

            <div class="flex-between" style="display: flex; justify-content: space-between; align-items: center;">
                <span style="font-size: 0.8rem; opacity: 0.7;">
                    {{ onpExportModal.items.filter(i => i.included).length }} of {{ onpExportModal.items.length }} compounds included
                </span>
                <button class="small" @click="confirmOnpExport"
                        :disabled="!onpExportModal.items.some(i => i.included)"
                        title="Export Robot Protocol (.onp) — Requires a valid Andrew+ license. Not affiliated with or endorsed by Waters Corporation.">
                    <i class="fas fa-robot"></i> Export .onp
                </button>
            </div>
        </div>
    </div>

    <!-- Grouped multi-plate .onp export -->
    <div v-if="showGroupExport" style="position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.6); display: flex; align-items: center; justify-content: center; z-index: 2000;">
        <div style="background: var(--surface); padding: 25px; border-radius: var(--radius); border: 1px solid var(--border); max-width: 560px; width: 90%; max-height: 80vh; overflow-y: auto;">
            <div class="flex-between" style="border-bottom: 1px solid var(--ln); padding-bottom: 10px; margin-bottom: 15px;">
                <h3 style="margin: 0; color: var(--primary);"><i class="fas fa-layer-group"></i> Group Plates → one .onp</h3>
                <button class="danger small" @click="showGroupExport = false"><i class="fas fa-times"></i></button>
            </div>

            <p style="margin: 0 0 14px 0; font-size: 0.82rem; opacity: 0.75;">
                Select the plates to combine. Each plate keeps its own target labware, but stocks shared
                between plates (matched by <strong>code + name</strong>) are merged into a single source
                holding the combined volume — every plate's pipetting steps draw from it.
            </p>

            <div class="input-group" style="margin-bottom: 14px;">
                <label style="font-size: 0.75rem; font-weight: bold;">Protocol / file name</label>
                <input type="text" v-model="groupExportName" placeholder="Grouped Plates" />
            </div>

            <div style="display: flex; flex-direction: column; gap: 8px; margin-bottom: 18px;">
                <label v-for="plt in exportableGroupPlates()" :key="'grp_'+plt.id"
                       style="display: flex; align-items: center; gap: 10px; background: var(--panel-bg); padding: 10px; border-radius: var(--radius); border: 1px solid var(--border); cursor: pointer;">
                    <input type="checkbox" v-model="groupSelection[plt.id]" style="width: 16px; height: 16px;" />
                    <div style="flex-grow: 1;">
                        <strong style="font-size: 1rem;">{{ plt.name }}</strong>
                        <div style="font-size: 0.72rem; opacity: 0.7;">
                            {{ plt.format }}-Well · {{ Object.keys(plt.wells || {}).filter(w => plt.wells[w] && plt.wells[w].trim() !== '').length }} filled wells
                        </div>
                    </div>
                </label>
                <div v-if="exportableGroupPlates().length === 0" style="font-size: 0.85rem; opacity: 0.5; font-style: italic;">
                    No robot-compatible, non-empty plates open. (Ibidi gamma chambers and 8 PCR strips are excluded.)
                </div>
            </div>

            <div class="flex-between" style="display: flex; justify-content: space-between; align-items: center;">
                <span style="font-size: 0.8rem; opacity: 0.7;">
                    {{ exportableGroupPlates().filter(p => groupSelection[p.id]).length }} selected
                </span>
                <button class="small" @click="exportAndrewPlusMulti"
                        :disabled="exportableGroupPlates().filter(p => groupSelection[p.id]).length < 2"
                        title="Export Robot Protocol (.onp) — Requires a valid Andrew+ license. Not affiliated with or endorsed by Waters Corporation.">
                    <i class="fas fa-robot"></i> Export Grouped .onp
                </button>
            </div>
        </div>
    </div>

    <div class="flex-between" style="border-bottom: 1px solid var(--ln); padding-bottom: 12px; margin-bottom: 20px; display: flex; justify-content: space-between;">
        <h2 style="border: none; padding: 0; margin: 0;"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3.5" width="12" height="9" rx="1.5"/><circle cx="5" cy="6.5" r="0.9"/><circle cx="8" cy="6.5" r="0.9"/><circle cx="11" cy="6.5" r="0.9"/><circle cx="5" cy="9.5" r="0.9"/><circle cx="8" cy="9.5" r="0.9"/><circle cx="11" cy="9.5" r="0.9"/></svg> Well Plate</h2>
        <div class="plate-toolbar">
            <button @click="showOnpSettings = !showOnpSettings" class="pt-btn" :class="{ on: showOnpSettings }" title="Robot Protocol Export Settings"><i class="fas fa-cog"></i> ONP</button>
            <button @click="openGroupExport" class="pt-btn" title="Combine multiple plates into one .onp (shared stocks merged)"><i class="fas fa-layer-group"></i> Group .onp</button>
            <button @click="onpInputRef.click()" class="pt-btn" :disabled="onpImportBusy"
                title="Read an Andrew+ .onp back into plates — every pipetting step replayed, with the concentration each well actually reached">
                <i class="fas" :class="onpImportBusy ? 'fa-spinner fa-spin' : 'fa-file-import'"></i> Import .onp
            </button>
            <input type="file" ref="onpInputRef" accept=".onp,.json,application/json" style="display:none" @change="importOnpFile" />
            <button @click="showCloudLibrary = true" class="pt-btn"><i class="fas fa-cloud"></i> Library</button>
            <button @click="addWellPlate" class="pt-btn primary"><i class="fas fa-plus"></i> New plate</button>
        </div>
    </div>

    <div v-if="showOnpSettings" style="margin-bottom: 20px; padding: 14px; background: var(--panel-bg); border: 1px solid var(--border); border-radius: var(--radius); font-size: 0.82rem;">
        <p style="margin: 0 0 10px 0; opacity: 0.7; font-style: italic;">
            Requires a valid Andrew+ license. Not affiliated with or endorsed by Waters Corporation.
            UUIDs below are read from your <code>.onp</code> files — update them if your installation uses different catalog identifiers.
        </p>
        <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px;">
            <div class="input-group" style="margin: 0;">
                <label style="font-size: 0.75rem; font-weight: bold;">Water Reagent UUID</label>
                <input type="text" v-model="onpConfig.waterReagentUuid" style="font-family: monospace; font-size: 0.75rem;" />
            </div>
            <div class="input-group" style="margin: 0;">
                <label style="font-size: 0.75rem; font-weight: bold;">Default Source Labware UUID</label>
                <input type="text" v-model="onpConfig.defaultSourceLabwareUuid" style="font-family: monospace; font-size: 0.75rem;" />
            </div>
            <div class="input-group" style="margin: 0;">
                <label style="font-size: 0.75rem; font-weight: bold;">Water Source Labware UUID</label>
                <input type="text" v-model="onpConfig.waterSourceLabwareUuid" style="font-family: monospace; font-size: 0.75rem;" />
            </div>
        </div>
    </div>

    <div v-for="(plate, pIndex) in store.wellPlates" :key="plate.id" style="background: var(--panel-bg); border: 1px solid var(--border); padding: 20px; border-radius: var(--radius); margin-bottom: 30px;">
        <div class="flex-between" style="margin-bottom: 20px; display: flex; justify-content: space-between; align-items: flex-end;">
            <div style="width: 35%; display: flex; gap: 15px; align-items: center;">
                <input type="text" v-model="plate.name" style="font-size: 1.2rem; font-weight: bold; flex-grow: 1; background: transparent; border: none; border-bottom: 2px solid var(--primary); padding-left: 0; color: var(--primary);">
                <select v-model="plate.format" @change="updateDefaultLabware(plate)" class="pt-select" style="width: 120px;">
                    <option :value="24">24-Well</option>
                    <option :value="48">48-Well</option>
                    <option :value="96">96-Well</option>
                    <option :value="384">384-Well</option>
                    <option :value="'ibidi'">Ibidi gamma chambers</option>
                    <option :value="'pcr8'">8 PCR strips</option>
                </select>
            </div>

            <!-- One control height, one shape, one filled button. What the plate IS
                 sits on the left, what you can DO with it in the middle, and the
                 four icon-only tools square off the end so the row stops ragged. -->
            <div class="plate-toolbar">
                <span class="scope-badge" :class="plate.scope === 'Global' ? 'lab' : 'private'">{{ plate.scope === 'Global' ? 'Lab' : 'Private' }}</span>
                <ExpStatusPicker :modelValue="plate.status || 'in_progress'" @update:modelValue="v => setPlanStatus(plate, v)" />

                <span class="pt-sep"></span>

                <button class="pt-btn primary" @click="store.saveToCloud('plates', plate); store.toast('Saved')" title="Save to cloud"><i class="fas fa-cloud-arrow-up"></i> Save</button>

                <template v-if="plate.owner_id === store.user.id">
                    <button class="pt-btn" v-if="plate.scope === 'Global'" @click="plate.scope = 'Personal'; store.saveToCloud('plates', plate); store.toast('Moved to Private')" title="Make private">
                        <i class="fas fa-user-lock"></i> Make private
                    </button>
                    <button class="pt-btn" v-else @click="plate.scope = 'Global'; store.saveToCloud('plates', plate); store.toast('Published to the lab')" title="Publish to the shared Lab space">
                        <i class="fas fa-bullhorn"></i> Publish
                    </button>
                </template>

                <span class="pt-sep"></span>

                <select v-model="plate.targetLabware" class="pt-select" title="Target labware for the robot protocol">
                    <option value="">Default target plate</option>
                    <option v-for="lw in store.targetLabwares.filter(l => l.format === plate.format)" :value="lw.uuid" :key="lw.uuid">{{ lw.name }}</option>
                </select>
                <button class="pt-btn" @click="savePlateToJournal(plate)" title="Log to Journal"><i class="fas fa-file-import"></i> Log</button>
                <button class="pt-btn" @click="openOnpExportModal(plate)" title="Export Robot Protocol (.onp) — choose which compounds to pipette. Requires a valid Andrew+ license. Not affiliated with or endorsed by Waters Corporation."><i class="fas fa-robot"></i> .onp</button>
                <button class="pt-btn" @click="exportPlateWorkbook(plate)" title="Excel workbook: one row per compound per well with stock, pipetted volume and the concentration reached, plus a per-well summary and a readable plate map."><i class="fas fa-file-excel"></i> Excel</button>
                <button class="pt-btn" @click="exportPlateYaml(plate)" title="YAML: the same data keyed by well — text, diffable, and readable by any script without a parser for our HTML."><i class="fas fa-file-code"></i> YAML</button>

                <span class="pt-sep"></span>

                <button class="pt-btn pt-icon" :class="{ on: plate.colorByCondition }" @click="plate.colorByCondition = !plate.colorByCondition" title="Colour wells by condition (Okabe-Ito)"><i class="fas fa-palette"></i></button>
                <button class="pt-btn pt-icon" @click="duplicatePlan(pIndex)" title="Duplicate"><i class="fas fa-copy"></i></button>
                <button class="pt-btn pt-icon" @click="archivePlan(pIndex)" title="Archive"><i class="fas fa-box-archive"></i></button>
                <button class="pt-btn pt-icon danger" @click="closeInWorkspace(pIndex)" title="Close from workspace"><i class="fas fa-times"></i></button>
            </div>
        </div>

        <div class="plate-container">
            <div class="plate-grid" :style="{ gridTemplateColumns: `30px repeat(${getPlateCols(plate.format)}, minmax(${plate.format === 384 ? '20px' : '30px'}, 1fr))` }">
                <div></div>
                <div v-for="c in getPlateCols(plate.format)" :key="'h'+c" class="plate-label">{{ c }}</div>
                
                <template v-for="r in getPlateRows(plate.format)" :key="'r'+r">
                    <div class="plate-label">{{ String.fromCharCode(64 + r) }}</div>
                    <div v-for="c in getPlateCols(plate.format)" :key="'w'+r+'-'+c"
                         :class="['well', { 'selected': plate.selectedWell === getWellId(r-1, c-1), 'has-content': plate.wells[getWellId(r-1, c-1)] && plate.wells[getWellId(r-1, c-1)].trim() !== '' }]"
                         :style="wellColor(plate, getWellId(r-1, c-1)) ? { background: wellColor(plate, getWellId(r-1, c-1)), borderColor: wellColor(plate, getWellId(r-1, c-1)) } : {}"
                         @click="selectWell(plate, getWellId(r-1, c-1))"
                         :title="getWellId(r-1, c-1)">
                    </div>
                </template>
            </div>
        </div>

        <!-- Condition legend (Okabe-Ito) -->
        <div v-if="plate.colorByCondition && plateGroups(plate).keys.length" class="plate-legend">
            <span v-for="k in plateGroups(plate).keys" :key="k" class="plate-legend-item">
                <span class="plate-legend-dot" :style="{ background: plateGroups(plate).colorMap[k] }"></span>
                {{ k }}
            </span>
        </div>

        <!-- Stocks used across the whole plate: one row per compound, changed everywhere at once. -->
        <div v-if="plateStocks(plate).length" style="margin-top:12px; border:1px solid var(--border); border-radius:var(--radius); background:var(--surface);">
            <div @click="showPlateStocks[plate.id] = !showPlateStocks[plate.id]"
                 style="padding:8px 14px; cursor:pointer; display:flex; align-items:center; gap:8px; font-size:0.85rem; font-weight:600;">
                <i class="fas" :class="showPlateStocks[plate.id] ? 'fa-chevron-down' : 'fa-chevron-right'" style="opacity:0.5;"></i>
                <i class="fas fa-vials" style="opacity:0.6;"></i>
                Stocks used in this plate
                <span style="opacity:0.55; font-weight:400;">({{ plateStocks(plate).length }} compound{{ plateStocks(plate).length === 1 ? '' : 's' }})</span>
                <span v-if="plateStocks(plate).some(s => !s.invId)" style="margin-left:auto; font-size:0.72rem; color:#d97706;">
                    <i class="fas fa-link-slash"></i> {{ plateStocks(plate).filter(s => !s.invId).length }} not linked to inventory
                </span>
            </div>
            <div v-if="showPlateStocks[plate.id]" style="padding:0 14px 12px;">
                <div style="font-size:0.72rem; opacity:0.6; margin-bottom:8px;">
                    Changing a stock here rewrites it in every well of this plate and recomputes what each well holds.
                    Linking an inventory item records which bottle was used — a well that already has its own recorded
                    stock keeps that value, since it is what was pipetted.
                </div>
                <div style="display:grid; grid-template-columns:1.8fr 90px 70px 90px 1fr; gap:8px; font-size:0.68rem; font-weight:700; opacity:0.55; padding-bottom:4px;">
                    <span>Compound</span><span>Stock</span><span>Unit</span><span>Wells</span><span>Inventory stock used</span>
                </div>
                <div v-for="s in plateStocks(plate)" :key="s.key"
                     style="display:grid; grid-template-columns:1.8fr 90px 70px 90px 1fr; gap:8px; align-items:center; padding:3px 0; font-size:0.82rem;">
                    <span style="white-space:nowrap; overflow:hidden; text-overflow:ellipsis;" :title="s.name">
                        {{ s.code ? '[' + s.code + '] ' : '' }}{{ s.name }}
                    </span>
                    <input type="number" step="any" min="0" :value="s.mixedStock ? null : s.stock"
                           :placeholder="s.mixedStock ? 'mixed' : '—'"
                           @change="setPlateStock(plate, s.key, 'stock', $event.target.value)"
                           style="padding:2px 5px; font-size:0.78rem; width:100%;"
                           :title="s.mixedStock ? 'Wells disagree on this stock — setting a value here makes them all the same' : ''">
                    <input type="text" :value="s.unit" @change="setPlateStock(plate, s.key, 'unit', $event.target.value)"
                           style="padding:2px 5px; font-size:0.78rem; width:100%;" placeholder="mM">
                    <span style="opacity:0.6; font-size:0.76rem;">{{ s.wells.length }} · {{ s.totalVolume.toFixed(1) }} µL</span>
                    <div style="position:relative;" @click.stop>
                        <div @click="activeDropdown = activeDropdown === 'stock_' + plate.id + s.key ? null : 'stock_' + plate.id + s.key"
                             style="padding:3px 8px; font-size:0.78rem; border-radius:var(--radius); border:1px solid var(--border); cursor:pointer; display:flex; align-items:center; gap:6px;"
                             :style="s.invId ? '' : 'border-style:dashed; opacity:0.75;'">
                            <span v-if="linkedShelf(s.invId)"
                                  :style="`flex:0 0 auto; font-size:0.6rem; font-weight:700; letter-spacing:0.04em; text-transform:uppercase; padding:1px 5px; border-radius:3px; color:#fff; background:${SHELVES[linkedShelf(s.invId)].color};`">
                                {{ SHELVES[linkedShelf(s.invId)].label }}
                            </span>
                            <i v-else class="fas fa-link" style="opacity:0.6; font-size:0.7rem;"></i>
                            <span style="white-space:nowrap; overflow:hidden; text-overflow:ellipsis;">
                                {{ s.invId ? (s.code ? '[' + s.code + '] ' : '') + s.name : 'link a stock…' }}
                            </span>
                            <i class="fas fa-chevron-down" style="opacity:0.4; margin-left:auto; font-size:0.7rem;"></i>
                        </div>
                        <div v-if="activeDropdown === 'stock_' + plate.id + s.key"
                             style="position:absolute; top:100%; right:0; z-index:1000; background:var(--surface); border:1px solid var(--border); box-shadow:0 4px 6px rgba(0,0,0,0.1); border-radius:var(--radius); min-width:310px;">
                            <div style="display:flex; gap:4px; padding:6px 6px 0;">
                                <button v-for="opt in [['Global','Lab inventory'],['Personal','Private inventory']]" :key="opt[0]"
                                        @click.stop="store.plateRefSearchScope = opt[0]" class="small"
                                        :style="store.plateRefSearchScope === opt[0] ? 'flex:1; padding:2px 6px; font-size:0.72rem;' : 'flex:1; padding:2px 6px; font-size:0.72rem; background:transparent; color:inherit; border:1px solid var(--border);'">
                                    {{ opt[1] }}
                                </button>
                            </div>
                            <input type="text" v-model="store.wellRtfSearchQuery" :placeholder="`Search ${store.plateRefSearchScope === 'Personal' ? 'private' : 'lab'} inventory…`"
                                   style="margin:5px; width:calc(100% - 10px); padding:4px; border:1px solid var(--border); border-radius:var(--radius);" @click.stop>
                            <div style="overflow-y:auto; max-height:220px;">
                                <div v-for="inv in stockPickList(store.wellRtfSearchQuery)" :key="inv.id"
                                     @mousedown.prevent="linkPlateStock(plate, s.key, inv)"
                                     style="padding:6px 10px; cursor:pointer; font-size:0.82rem; border-bottom:1px solid var(--bg); display:flex; align-items:center; gap:7px;">
                                    <span style="min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;">
                                        [{{ inv.code }}] {{ inv.name }} ({{ store.formatNum(inv.stock) }} {{ inv.stockUnit || 'µM' }})
                                    </span>
                                </div>
                                <div v-if="!stockPickList(store.wellRtfSearchQuery).length" style="padding:8px 10px; font-size:0.78rem; opacity:0.55;">
                                    Nothing in the {{ store.plateRefSearchScope === 'Personal' ? 'private' : 'lab' }} inventory matches — try the other shelf.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div v-if="plate.selectedWell" class="well-editor-panel">
            <div style="background: var(--summary-bg); padding: 8px 15px; border-bottom: 1px solid var(--border); font-weight: bold; display: flex; justify-content: space-between; align-items: center;">
                <span><i class="fas fa-crosshairs"></i> Editing Well: <span style="color: var(--primary); font-size: 1.1rem;">{{ plate.selectedWell }}</span></span>
                <span style="display: flex; align-items: center; gap: 6px;">
                    <span style="font-size: 0.8rem; font-weight: normal; opacity: 0.7; margin-right: 4px;">Click any well above to edit</span>
                    <button class="pt-btn" @click="copyWell(plate)"
                            title="Copy this well's content — then select a well on any plate and paste">
                        <i class="fas fa-copy"></i> Copy well
                    </button>
                    <button class="pt-btn" @click="pasteWell(plate)" :disabled="!wellClipboard"
                            :title="wellClipboard ? `Paste ${wellClipboard.from} into ${plate.selectedWell} (replaces its content)` : 'Nothing copied yet'">
                        <i class="fas fa-paste"></i> Paste
                    </button>
                </span>
            </div>
            <div class="rtf-toolbar" style="border-bottom: 1px solid var(--border);">
                <button class="rtf-btn" @click.prevent="formatWellDoc(plate, 'bold')" title="Bold"><i class="fas fa-bold"></i></button>
                <button class="rtf-btn" @click.prevent="formatWellDoc(plate, 'italic')" title="Italic"><i class="fas fa-italic"></i></button>
                <button class="rtf-btn" @click.prevent="formatWellDoc(plate, 'underline')" title="Underline"><i class="fas fa-underline"></i></button>
                <div style="width: 1px; background: var(--border); margin: 0 4px; height: 24px;"></div>
                <div style="position: relative; margin-left: auto;" @click.stop>
                    <div @click="activeDropdown = activeDropdown === 'plate_ref_' + plate.id ? null : 'plate_ref_' + plate.id" style="padding: 4px 8px; font-size: 0.85rem; border-radius: var(--radius); border: 1px solid var(--border); background: var(--surface); color: var(--text); cursor: pointer; height: 32px; display: flex; align-items: center; gap: 6px;">
                        <span>+ Reference Stock</span>
                        <i class="fas fa-chevron-down" style="opacity: 0.5;"></i>
                    </div>
                    <div v-if="activeDropdown === 'plate_ref_' + plate.id" style="position: absolute; top: 100%; right: 0; z-index: 1000; background: var(--surface); border: 1px solid var(--border); box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: var(--radius); min-width: 250px; display: flex; flex-direction: column;">
                        <div style="display: flex; gap: 4px; padding: 6px 6px 0;">
                            <button v-for="opt in [['Global','Lab inventory'],['Personal','Private inventory']]" :key="opt[0]"
                                    @click.stop="store.plateRefSearchScope = opt[0]" class="small"
                                    :style="store.plateRefSearchScope === opt[0] ? 'flex:1; padding:2px 6px; font-size:0.72rem;' : 'flex:1; padding:2px 6px; font-size:0.72rem; background:transparent; color:inherit; border:1px solid var(--border);'">
                                {{ opt[1] }}
                            </button>
                        </div>
                        <input type="text" v-model="store.wellRtfSearchQuery" :placeholder="`Search ${store.plateRefSearchScope === 'Personal' ? 'private' : 'lab'} inventory…`" style="margin: 5px; width: calc(100% - 10px); padding: 4px; border: 1px solid var(--border); border-radius: var(--radius);" @click.stop>
                        <div style="overflow-y: auto; max-height: 200px;">
                            <div v-for="inv in stockPickList(store.wellRtfSearchQuery)" :key="inv.id" @mousedown.prevent="store.selectedWellInvRef = inv.id; insertInventoryRefToWell(plate); activeDropdown = null" style="padding: 6px 10px; cursor: pointer; font-size: 0.85rem; border-bottom: 1px solid var(--bg); display:flex; align-items:center; gap:7px;" onmouseover="this.style.background='var(--summary-bg)'" onmouseout="this.style.background='transparent'">
                                <span style="min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;">
                                    [{{ inv.code }}] {{ inv.name }} ({{store.formatNum(inv.stock)}} {{inv.stockUnit || 'µM'}})
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- What is actually in this well. The stock is editable per well: a well
                 records the stock that went into IT, which is not always what the
                 inventory says today (an older bottle, a fresh dilution). Changing it
                 recomputes the concentration reached and never touches the inventory. -->
            <div v-if="wellRows(plate).length" style="padding:8px 12px; border-bottom:1px solid var(--border); background:var(--summary-bg);">
                <div style="display:grid; grid-template-columns:1.6fr 84px 96px 60px 1fr; gap:6px; font-size:0.68rem; font-weight:700; opacity:0.55; padding-bottom:4px;">
                    <span>Component</span><span>Volume µL</span><span>Stock used</span><span>Unit</span><span>Actually in the well</span>
                </div>
                <div v-for="(row, ri) in wellRows(plate)" :key="ri"
                     style="display:grid; grid-template-columns:1.6fr 84px 96px 60px 1fr; gap:6px; align-items:center; font-size:0.8rem; padding:2px 0;">
                    <span style="white-space:nowrap; overflow:hidden; text-overflow:ellipsis;" :title="row.name">
                        <i class="fas" :class="row.kind === 'water' ? 'fa-droplet' : 'fa-tag'" style="opacity:0.5; font-size:0.7rem;"></i>
                        {{ row.code ? '[' + row.code + '] ' : '' }}{{ row.name }}
                    </span>
                    <input type="number" step="any" min="0" :value="row.volume"
                           @change="setWellEntry(plate, ri, 'volume', $event.target.value)"
                           style="padding:2px 5px; font-size:0.78rem; width:100%;">
                    <input v-if="row.kind === 'reagent'" type="number" step="any" min="0" :value="row.stock"
                           @change="setWellEntry(plate, ri, 'stock', $event.target.value)"
                           style="padding:2px 5px; font-size:0.78rem; width:100%;" placeholder="—">
                    <span v-else style="opacity:0.35;">—</span>
                    <input v-if="row.kind === 'reagent'" type="text" :value="row.unit"
                           @change="setWellEntry(plate, ri, 'unit', $event.target.value)"
                           style="padding:2px 5px; font-size:0.78rem; width:100%;" placeholder="mM">
                    <span v-else style="opacity:0.35;">—</span>
                    <span v-if="row.final != null" style="font-variant-numeric:tabular-nums;">
                        <strong>{{ fmtConc(row.final) }}</strong> {{ row.unit }}
                    </span>
                    <span v-else style="opacity:0.4;">{{ row.kind === 'water' ? 'fill-up' : 'no stock recorded' }}</span>
                </div>
                <div style="margin-top:5px; font-size:0.72rem; display:flex; gap:10px; align-items:center;">
                    <span :style="plate.targetVolume && wellTotal(plate) > plate.targetVolume + 1e-9 ? 'color:#ef4444; font-weight:700;' : 'opacity:0.6;'">
                        Σ {{ wellTotal(plate).toFixed(2) }} µL<span v-if="plate.targetVolume"> of {{ plate.targetVolume }} µL</span>
                    </span>
                    <span v-if="plate.targetVolume && wellTotal(plate) > plate.targetVolume + 1e-9" style="color:#ef4444;">
                        overfilled — the concentrations above are what this well really holds, not what was planned
                    </span>
                    <span v-if="wellUnlinked(plate).total > 0" style="color:#f59e0b;"
                          :title="'These lines state a volume but carry no inventory chip, so nothing records which stock they came from. They are not in the Σ and the robot export skips them. Add a chip to include them.'">
                        <i class="fas fa-triangle-exclamation"></i>
                        + {{ wellUnlinked(plate).total.toFixed(2) }} µL not linked to a stock ({{ wellUnlinked(plate).names }}) — not counted, not exported
                    </span>
                    <label style="margin-left:auto; opacity:0.75; display:flex; gap:5px; align-items:center;"
                           title="Re-make this well at a different total volume: every component (fill-up included) is scaled by the same factor, so all concentrations stay exactly what they are — only the pipetted volumes change.">
                        <i class="fas fa-compress-arrows-alt" style="opacity:0.6;"></i> scale Σ to
                        <input type="number" step="any" min="0" placeholder="µL"
                               @change="scaleWellTo(plate, $event.target.value); $event.target.value = ''"
                               style="padding:2px 5px; font-size:0.75rem; width:70px;">
                    </label>
                    <label style="opacity:0.6; display:flex; gap:5px; align-items:center;">
                        well volume
                        <input type="number" step="any" min="0" v-model.number="plate.targetVolume" @change="store.saveWorkspaceState()"
                               placeholder="—" style="padding:2px 5px; font-size:0.75rem; width:70px;">
                    </label>
                </div>
            </div>

            <div class="journal-textarea rtf-editor"
                 contenteditable="true"
                 placeholder="Type contents, concentrations, or insert stock references..."
                 style="border: none; border-radius: 0; outline: none; min-height: 100px;"
                 @input="updateWellContent(plate, $event)"
                 @blur="updateWellContent(plate, $event)"
                 :id="'wellEditor_' + plate.id">
            </div>
        </div>
        <div v-else style="margin-top: 15px; text-align: center; padding: 20px; background: var(--surface); border: 1px dashed var(--border); border-radius: var(--radius); opacity: 0.6;">
            Select a well to edit its contents.
        </div>
    </div>
  </div>
</template>

<style scoped>
.plate-legend {
  display: flex; flex-wrap: wrap; gap: 8px 16px;
  margin-top: 12px; padding: 10px 12px;
  background: var(--fl); border-radius: var(--rc);
  font-size: 0.78rem; color: var(--tx);
}
.plate-legend-item { display: inline-flex; align-items: center; gap: 6px; }
.plate-legend-dot { width: 12px; height: 12px; border-radius: 3px; flex: none; box-shadow: inset 0 0 0 1px rgba(0,0,0,.12); }

/* Plate toolbar ------------------------------------------------------------
   Every control on one row is the same height and the same radius, and only the
   action you came for is filled. The icon-only tools are square, so the row ends
   on a straight edge instead of on three buttons of three widths. */
.plate-toolbar { display: flex; align-items: center; justify-content: flex-end; gap: 6px; flex-wrap: wrap; min-width: 0; }

.pt-btn {
  height: 30px; padding: 0 11px; border-radius: 8px;
  font-size: 0.74rem; font-weight: 600; line-height: 1; white-space: nowrap;
  display: inline-flex; align-items: center; justify-content: center; gap: 6px;
  background: var(--btn2, rgba(0,0,0,.05)); color: var(--tx, inherit);
  border: 1px solid var(--ln2, rgba(0,0,0,.12));
  box-shadow: none; cursor: pointer; transition: filter .15s, background .15s, color .15s, border-color .15s;
}
.pt-btn:hover:not(:disabled) { filter: brightness(1.06); }
.pt-btn:disabled { opacity: .55; cursor: default; }
.pt-btn i { font-size: 0.78rem; }

/* One filled button per row — the action you came to this row for. */
.pt-btn.primary { background: var(--acc, #2563eb); border-color: transparent; color: #fff; }
/* A toggle that is currently on. */
.pt-btn.on { background: var(--acs, rgba(37,99,235,.14)); border-color: var(--acc, #2563eb); color: var(--acc, #2563eb); }
/* Destructive: quiet until you reach for it. */
.pt-btn.danger:hover { background: var(--danger-color, #ef4444); border-color: transparent; color: #fff; filter: none; }

.pt-icon { width: 30px; padding: 0; }
.pt-icon i { font-size: 0.8rem; }

.pt-select {
  height: 30px; max-width: 170px; padding: 0 8px; border-radius: 8px;
  font-size: 0.74rem; color: inherit;
  background: var(--fl, transparent); border: 1px solid var(--ln2, rgba(0,0,0,.12));
}

.pt-sep { width: 1px; height: 18px; background: var(--ln2, rgba(0,0,0,.12)); margin: 0 2px; flex: none; }
</style>